# general settings
name: train_RealESRGANx2_patches
model_type: RealESRGANModel
scale: 2
num_gpu: auto
manual_seed: 0

# ----------------- options for synthesizing training data in RealESRGANModel ----------------- #
# USM the ground-truth
l1_gt_usm: False
percep_gt_usm: False
gan_gt_usm: False

high_order_degradation: False

gt_size: 64
queue_size: 512

# dataset and data loader settings
datasets:
  train:
    name: BP
    type: RealESRGANPairedDataset
    dataroot_gt: D:/Octavo Semestre/PFC/Implementacion/Tecnica Nueva/Real-ESRGAN/datasets/train/
    dataroot_lq: D:/Octavo Semestre/PFC/Implementacion/Tecnica Nueva/Real-ESRGAN/datasets/train/
    meta_info: D:/Octavo Semestre/PFC/Implementacion/Tecnica Nueva/Real-ESRGAN/datasets/archivo.zip  
    io_backend:
      type: disk

    gt_size: 64
    use_hflip: True
    use_rot: True

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  # Uncomment these for validation
  val:
    name: validation
    type: RealESRGANPairedDataset
    dataroot_gt: D:/Octavo Semestre/PFC/Implementacion/Tecnica Nueva/Real-ESRGAN/datasets/val/
    dataroot_lq: D:/Octavo Semestre/PFC/Implementacion/Tecnica Nueva/Real-ESRGAN/datasets/val/
    meta_info: D:/Octavo Semestre/PFC/Implementacion/Tecnica Nueva/Real-ESRGAN/datasets/archivo.zip  # <-- Ajuste aquí
    io_backend:
      type: disk

# network structures
network_g:
  type: RRDBNet
  num_in_ch: 1
  num_out_ch: 1
  num_feat: 40
  num_block: 16
  num_grow_ch: 20
  scale: 2

network_d:
  type: UNetDiscriminatorSN
  num_in_ch: 1
  num_feat: 40
  skip_connection: True

# path
path:
  pretrain_network_g: experiments/train_RealESRNetx2_patches/models/net_g_1000000.pth
  param_key_g: params_ema
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000]
    gamma: 0.5

  total_iter: 400000
  warmup_iter: -1

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1
      'conv4_4': 1
      'conv5_4': 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: !!float 0.75
    style_weight: !!float 0.25
    range_norm: false
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 1e-1

  net_d_iters: 1
  net_d_init_iters: 0

# Uncomment these for validation
# validation settings
val:
  val_freq: !!
